import os
import sys
try:
    from google.cloud import storage
except ImportError:
    print("Please install google-cloud-storage: pip install google-cloud-storage")
    sys.exit(1)

def download_cloud_data(bucket_name, download_dest):
    """Pulls Eureka plots and ansatz generated by the Vertex AI Swarm."""
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)

    blobs = bucket.list_blobs(prefix="latest_eureka")
    
    if not os.path.exists(download_dest):
        os.makedirs(download_dest)

    count = 0
    for blob in blobs:
        # Create local directory recursively
        local_path = os.path.join(download_dest, blob.name)
        
        local_dir = os.path.dirname(local_path)
        if not os.path.exists(local_dir):
            os.makedirs(local_dir)
            
        blob.download_to_filename(local_path)
        print(f"📥 Pulled: {local_path}")
        count += 1
        
    if count == 0:
        print(f"⚠️ No data found in bucket '{bucket_name}' under prefix 'latest_eureka'. Swarm might still be running or hasn't found a solution yet.")
    else:
        print(f"✅ Successfully pulled {count} files from Vertex AI!")

if __name__ == "__main__":
    bname = os.getenv("GCP_BUCKET_NAME", "autowarp-swarm-data")
    dest = os.path.join(os.path.dirname(__file__), "cloud_downloads")
    print(f"Conectando a GCP Bucket: {bname} ...")
    download_cloud_data(bname, dest)
